### ISSUE TITLE
Feat: Allow the use of Equals

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/SharpResume#2]
Hello,

I think it would be nice to allow the user to compare two resumes or let him implement a HashTable of resume. For this, we need a proper override of `Equals()` and `GetHashCode()`.

Cheers,

**Comment by aloisdg** [comment]
I implemented `Equals()`, `GetHashCode()`, `==` and "!=" in my [last commit](https://github.com/aloisdg/SharpResume/commit/82980e63cca46781dfb2ad6fe8d39c5bae5e8ae3) with R#.

I found online a library to remove this boilerplate code : [ValueUtils](https://github.com/EamonNerbonne/ValueUtils) by @EamonNerbonne. I may switch to it.

**Comment by EamonNerbonne** [comment]
Hope it's helpful - if there's anything unclear or there are any missing features, please give a shout - I'm still actively maintaining the lib!

**Comment by aloisdg** [comment]
Your lib seems nice. I will start to play with it later. Thank you for created it!
